### ISSUE TITLE
Is pll calculation correct ? 

### ISSUE THREAD

**Issue by sezgin-akbayin** [donghao2nanjing/PLL#2]
float calc_pll_sogi(PLL_SOGI_t *s, float signal) {
    float error;
//////////////////////////////////////////////////////////////
    error = signal - s->sogi_forward_integrator_output; //-> Hey, dude This line is useless !? Please look next line
/////////////////////////////////////////////////////////////
    error = s->ke * error;
    error -= s->sogi_backward_integrator_output * s->angle_freq;
    error *= s->angle_freq;
    s->sogi_forward_integrator_output += error * s->update_period;

    s->sogi_backward_integrator_output += s->sogi_forward_integrator_output * s->update_period;

    error = s->sogi_forward_integrator_output * cos(s->phase_output) +
            s->sogi_backward_integrator_output * s->angle_freq * sin(s->phase_output);
    s->loop_filter_sum += error * s->loop_filter_ki;
    s->angle_freq = s->center_angle_freq + s->loop_filter_sum + s->loop_filter_kp * error;
    s->phase_output += s->angle_freq * s->update_period;

    if (s->phase_output > 2 * M_PI) {
        s->phase_output -= 2 * M_PI;
    }

    return s->phase_output;
}

**Comment by haodongnj** [comment]
Anything wrong with the calculation?  I have validated it with [examples/SOGI_PLL/test_sogi_pll.c](https://github.com/haodongnj/PLL/blob/master/examples/SOGI_PLL/test_sogi_pll.c) .

**Comment by sezgin-akbayin** [comment]
I'm sorry, my bad ! :-)
